import sys
import os

# Handle ChromeDriver path when compiled
if getattr(sys, 'frozen', False):
    # Running as compiled executable
    chromedriver_path = os.path.join(os.path.dirname(sys.executable), 'chromedriver')
else:
    # Running as script - use webdriver-manager
    from webdriver_manager.chrome import ChromeDriverManager
    chromedriver_path = ChromeDriverManager().install()

# Then use in your Service initialization
service = Service(executable_path=chromedriver_path)
